### ISSUE TITLE
Cannot find DATASET_NAME.csv files required in Final DeToxy-B Transcript Prep.ipynb

### ISSUE THREAD

**Issue by yangbai8** [Sreyan88/Toxicity-Detection-in-Spoken-Utterances#2]
I am not an expert so may need more help from you. In the Final DeToxy-B Transcript Prep.ipynb, for each dataset, you first read a csv file, e.g., MELD.csv. I cannot find this kind of csv file anywhere. Would you please help?

Your help is much appreciated!

**Comment by Sreyan88** [comment]
@SamdenLepcha can you please address this.

**Comment by SamdenLepcha** [comment]
Hi @yangbai8! The Final DeToxy-B Transcript Prep code uses an intermediate file that we have prepared and manually annotated for toxicity. To create this for MELD you can download the MELD dataset from this link: https://affective-meld.github.io/ . After downloading the raw files, you have the transcripts present and use that file. But these won't contain the toxicity labels that the team has worked hard to create. 

Alternatively, you can directly use the annotated files in the data folder. They are train.csv, test.csv, valid.csv, and trigger_test.csv. Then you can download the audio files and use the audio prep code to recreate our DeToxy Dataset. 

Hope this helps.
